version check

diff --git a/.github/actions/setup-git-credentials/action.yaml b/.github/actions/setup-git-credentials/action.yaml
--- a/.github/actions/setup-git-credentials/action.yaml
+++ b/.github/actions/setup-git-credentials/action.yaml
@@ -3,10 +3,12 @@ description: Sets up Git credentials for the action
 runs:
   using: "composite"
   steps:
-    - name: Set Git user name and email
+    - name: Check version in package.json
       run: |
-        # Below are credentials for the built-in GitHub Actions bot: https://github.com/orgs/community/discussions/26560
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-        git config --global push.followTags true
+        main_package_version=$(git show main:package.json | grep version | head -n 1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')
+        current_package_version=$(node -pe "require('./package.json').version")
+        if [ "$main_package_version" != "$current_package_version" ]; then
+         echo "Error: Package version on current branch ($current_package_version) does not match the one on main branch ($main_package_version)"
+        exit 1
+        fi
       shell: bash
