c44

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -31,9 +31,7 @@ jobs:
       - name: Check for test.only in test.ts files
         run: |
           if grep -r -l 'test.only' ./test/**/*.ts; then
-            echo "Error: Found /test.only/ in one of test files"
-            exit 1
-          else
-            echo "No instances of /test.only/ found in test files"
+            echo "Error: Found /test.only/ in one of test files";
+            exit 1;
           fi
 
